version: 2

project_name: atun

builds:
  - id: atun
    main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
#      - windows # disabled for now
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X version.version={{.Version}}

archives:
  - id: release_archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

release:
  github:
    owner: automationd
    name: atun
  draft: false

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

brews:
  - name: atun
    alternative_names:
      - "atun@{{ .Version }}"
    repository:
      owner: AutomationD
      name: homebrew-tap
    url_template: "https://github.com/automationd/atun/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Dmitry Kireev
      email: dmitry@atd.sh
    directory: Formula
    homepage: "https://github.com/automationd/atun"
    description: "atun - Atun - AWS Tagged Tunnel"
    license: "Apache 2.0"
    test: |
      system "#{bin}/atun version"
    install: |
      bin.install "atun"
