# This is a sample config file that is used when atun cli is ued to deploy a Router Host.
# It's not required when connecting to an existing Router Host that is tagged with atun-compatible tags.

aws_region="us-east-1"
router_subnet_id="subnet-xxxxxxxxxxxxxxxx"

[[hosts]]
name = "ipconfig.io"
proto = "ssm"
remote = 80
local = 10080

[[hosts]]
name = "icanhazip.com"
proto = "ssm"
remote = 80
local = 10081

#[[hosts]]
#name = "target-vpc-host-3"
#proto = "ssm"
#remote = "443"
#local = "10003"
#
#[[hosts]]
#name = "target-vpc-host-4"
#proto = "ssm"
#remote = "4444"
#local = "10005"
