name: Release Build
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  release:
    types:
      - created

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  goreleaser:
    name: Build and Release with GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install Alpine tools
        run: sudo apk add --no-cache alpine-sdk

      - name: Setup signing keys
        env:
          ALPINE_PRIVATE_KEY: ${{ secrets.ALPINE_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.alpine
          echo "$ALPINE_PRIVATE_KEY" > ~/.alpine/atun.rsa
          chmod 600 ~/.alpine/atun.rsa

      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean -f .goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          RELEASE_VERSION: "${{ env.RELEASE_VERSION }}"
          FURY_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
          GIT_SHA: ${{ env.SHORT_SHA }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Sign APK files
        run: |
          for apk in dist/*.apk; do
            if [ -f "$apk" ]; then
              abuild-sign -k ~/.alpine/atun.rsa "$apk"
            fi
          done

      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "${{ env.RELEASE_VERSION }}" --draft=false --latest=false
