name: Dev Build
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  RELEASE_VERSION: 0.0.0

jobs:
  goreleaser:
    name: Build and Release with GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Set env
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Delete existing tag
        run: |          
          git config --global user.email "dmitry@atd.sh"
          git config --global user.name "Dmitry Kireev"
          git tag -d "${{ env.RELEASE_VERSION }}" || echo "No tag to delete"
          git push origin :refs/tags/${{ env.RELEASE_VERSION }} || echo "No remote tag to delete"

      - name: Add tag
        run: |
          git tag -a ${{ env.RELEASE_VERSION }} -m "Development release"          
          git push origin ${{ github.ref_name }}

      - name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean -f .goreleaser.dev.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          RELEASE_VERSION: "${{ env.RELEASE_VERSION }}"
          FURY_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
          GIT_SHA: ${{ env.SHORT_SHA }}
          GITHUB_ACTOR: ${{ github.actor }}


      - name: Publish release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "${{ env.RELEASE_VERSION }}" --draft=false --latest=false
