name: Release Pipeline

on:
  push:
    branches:
      - main
#    tags:
#      - "*.*.*"
#      - "*.*.*-dev"


permissions:
  contents: write

jobs:
  goreleaser:
    name: Build and Release with GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Set env
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Delete existing release and tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete "0.0.0-dev" --yes || echo "No release to delete"
          git tag -d "0.0.0-dev" || echo "No tag to delete"
          git push origin :refs/tags/0.0.0-dev || echo "No remote tag to delete"

      # Add 0.0.0-dev tag
      - name: Add tag
        run: |
          git tag -a 0.0.0-dev -m "Development release"
          git config --global user.email "dmitry@atd.sh"
          git config --global user.name "Dmitry Kireev"
          git push origin ${{ github.ref_name }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
          RELEASE_VERSION: "${{ env.SHORT_SHA }}"
#          FURY_TOKEN: ${{ secrets.FURY_PUSH_TOKEN }}
          GIT_SHA: ${{ env.SHORT_SHA }}
          GITHUB_ACTOR: ${{ github.actor }}
